#!/usr/bin/env bash
# a Bash script that gives you information about the school file.

file="school"
if [ -e "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ] # space needed after not(!) to inverse the boolean result
    then
        echo "school file is empty"
    fi
    if [ -s "$file" ]   # the option s checks is true if file size is non-zero
    then
        echo "school file is not empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
